### ISSUE TITLE
Cannot connect to onedrive

### ISSUE THREAD

**Issue by MichelJanssens** [gogolith/GoCoEdit#48]
Well, the subject says it all. My account supposedly does not exist. It does, I checked it.

**Comment by gogolith** [comment]
Hi MichelJanssens, GoCoEdit only supports plain OneDrive accounts / OneDrive for Office 365 or Business are not supported at this moment.

**Comment by MichelJanssens** [comment]
That makes it impossible to work on my files on my work account (our sysadmin does not allow personal onedrives). When is it to be expected to work on the pro-versions as well?

**Comment by gogolith** [comment]
it's planed for the overnext mayor release by the end of the year. (GCE >=15)

**Comment by gogolith** [comment]
Should work since GCE 15
