### ISSUE TITLE
Can not preview JS and HTML at the same time?

### ISSUE THREAD

**Issue by brendanjb91** [gogolith/GoCoEdit#69]
Got some html which previews fine.

As soon as I add a JS (either in external file or in html) it stops the rest of the html loading

Any reason why?

**Comment by brendanjb91** [comment]
Works in safari but not internal browser

**Comment by gogolith** [comment]
Hi brendanjb91, can you provide some example code to reproduce this behavior... Thank you.

**Comment by allyouaskfor** [comment]
Make sure the JS is in the correct area, either in the header or the end of the body, and make sure the formatting is all correct. I'm able to load external JS and inline JS within an HTML document no problem. It's working in Safari, internal browser, and I'm able to manually load the local address from GoCoEdit into the Alook browser. (Alook offers the ability to customize user agents and gives access to a console)

5th Gen iPad running iOS 12.1.
