### ISSUE TITLE
fuzzy search not working?

### ISSUE THREAD

**Issue by scottkf** [gogolith/GoCoEdit#71]
After pushing the shortcut key for file traversal it seems like fuzzy search isn’t working. Is it not implemented? Is there anyway to find a file without traversing the structure?

**Comment by gogolith** [comment]
The search works on listed (traversing) or recent files.

**Comment by scottkf** [comment]
thanks @gogolith - is there a reason why it’s not supported today? can it be? is it on the roadmap?

how long does the recent file list stay recent? how many can be recent?

**Comment by gogolith** [comment]
Because GCE is focused for remote editing and indexing any files on your server in the background could be network and performance heavy. 
Recent files are cleared if you switch the remote....
